name: tests

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build extension
        run: yarn build
      - name: Install PlaydateSDK (macOS)
        run: |
          wget https://download.panic.com/playdate_sdk/PlaydateSDK-1.12.3.zip
          unzip PlaydateSDK-1.12.3.zip
          xar -xf PlaydateSDK-1.12.3.pkg
          cat PlaydateSDK.pkg/Payload | gunzip -dc | cpio -i
          rm -rf fixtures/PlaydateSDK-1.12.3
          mv PlaydateSDK fixtures/PlaydateSDK-1.12.3
        if: false
      - name: Install PlaydateSDK (Linux)
        run: |
          wget https://download.panic.com/playdate_sdk/Linux/PlaydateSDK-1.12.3.tar.gz
          tar xfz PlaydateSDK-1.12.3.tar.gz -C fixtures/
        if: runner.os == 'Linux'
      - name: Run tests (Linux)
        run: xvfb-run -a yarn test:coverage
        if: runner.os == 'Linux'
      - name: Run tests
        run: yarn test:coverage
        if: runner.os != 'Linux'
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: yarn run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
